#!/usr/bin/env python3
"""Generate schema-compatible fallback CSV when Kaggle file is not present (80 rows).

Does not overwrite a real Kaggle download (~1500 rows). Use import_kaggle_csv.sh instead.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from ai_jobs_data import DEFAULT_RAW, DOWNLOADS_CSV, is_kaggle_dataset, row_count

OUT = DEFAULT_RAW

COLUMNS = [
    "job_id",
    "job_title",
    "job_category",
    "experience_level",
    "years_of_experience",
    "education_required",
    "annual_salary_usd",
    "salary_min_usd",
    "salary_max_usd",
    "city",
    "country",
    "remote_work",
    "company_size",
    "industry",
    "required_skills",
    "ai_salary_premium_pct",
    "demand_score",
    "demand_growth_yoy_pct",
    "benefits_score_10",
    "posting_year",
    "posting_month",
    "is_senior",
    "is_remote_friendly",
    "is_llm_role",
    "salary_tier",
]


def row(
    job_id: str,
    title: str,
    category: str,
    exp: str,
    yoe: int,
    edu: str,
    annual: float,
    smin: int,
    smax: int,
    city: str,
    country: str,
    remote: str,
    size: str,
    industry: str,
    skills: str,
    premium: float,
    demand: int,
    growth: float,
    benefits: float,
    year: int,
    month: int,
    senior: int,
    remote_ok: int,
    llm: int,
    tier: str,
) -> dict:
    return {
        "job_id": job_id,
        "job_title": title,
        "job_category": category,
        "experience_level": exp,
        "years_of_experience": yoe,
        "education_required": edu,
        "annual_salary_usd": annual,
        "salary_min_usd": smin,
        "salary_max_usd": smax,
        "city": city,
        "country": country,
        "remote_work": remote,
        "company_size": size,
        "industry": industry,
        "required_skills": skills,
        "ai_salary_premium_pct": premium,
        "demand_score": demand,
        "demand_growth_yoy_pct": growth,
        "benefits_score_10": benefits,
        "posting_year": year,
        "posting_month": month,
        "is_senior": senior,
        "is_remote_friendly": remote_ok,
        "is_llm_role": llm,
        "salary_tier": tier,
    }


def _seed_rows() -> list[dict]:
    """Curated rows so Part 2 evaluation queries have grounded answers."""
    seeds = [
        row(
            "JOB-IC-001",
            "Senior Machine Learning Engineer",
            "Machine Learning",
            "Senior",
            8,
            "MS",
            285000,
            260000,
            310000,
            "Seattle",
            "United States",
            "Hybrid",
            "Large",
            "Technology",
            "PyTorch; modeling; individual contributor; no direct reports",
            18.0,
            92,
            12.5,
            8.5,
            2025,
            11,
            1,
            0,
            0,
            "High",
        ),
        row(
            "JOB-IC-002",
            "Research Scientist",
            "Research",
            "Senior",
            6,
            "PhD",
            310000,
            290000,
            340000,
            "San Francisco",
            "United States",
            "Remote",
            "Large",
            "Technology",
            "deep learning; hands-on experiments; individual contributor",
            22.0,
            88,
            15.0,
            9.0,
            2025,
            10,
            1,
            1,
            1,
            "High",
        ),
        row(
            "JOB-REMOTE-001",
            "Machine Learning Engineer",
            "Machine Learning",
            "Mid",
            4,
            "BS",
            215000,
            200000,
            230000,
            "Austin",
            "United States",
            "Remote",
            "Medium",
            "Technology",
            "scikit-learn; MLOps; fully distributed team",
            12.0,
            85,
            10.0,
            7.5,
            2025,
            9,
            0,
            1,
            0,
            "High",
        ),
        row(
            "JOB-REMOTE-002",
            "Applied Scientist",
            "Machine Learning",
            "Senior",
            7,
            "MS",
            245000,
            230000,
            265000,
            "Toronto",
            "Canada",
            "Remote",
            "Large",
            "Technology",
            "NLP; transformers; work from anywhere policy",
            15.0,
            80,
            9.0,
            8.0,
            2025,
            8,
            1,
            1,
            1,
            "High",
        ),
        row(
            "JOB-ENTRY-001",
            "Junior Data Analyst",
            "Data Science",
            "Entry",
            0,
            "BS",
            52000,
            48000,
            56000,
            "Berlin",
            "Germany",
            "On-site",
            "Small",
            "Consulting",
            "SQL; dashboards; first role; graduate friendly",
            5.0,
            70,
            8.0,
            6.0,
            2025,
            6,
            0,
            0,
            0,
            "Low",
        ),
        row(
            "JOB-ENTRY-002",
            "Associate ML Engineer",
            "Machine Learning",
            "Entry",
            1,
            "BS",
            78000,
            72000,
            84000,
            "Bangalore",
            "India",
            "Hybrid",
            "Medium",
            "Technology",
            "Python; mentorship; early career; starter role",
            8.0,
            75,
            11.0,
            6.5,
            2025,
            7,
            0,
            0,
            0,
            "Mid",
        ),
        row(
            "JOB-NLP-001",
            "Staff NLP Engineer",
            "Natural Language Processing",
            "Staff",
            10,
            "MS",
            395000,
            370000,
            420000,
            "New York",
            "United States",
            "Hybrid",
            "Large",
            "Technology",
            "large language models; NLP; tokenization; RAG",
            25.0,
            95,
            18.0,
            9.2,
            2025,
            12,
            1,
            0,
            1,
            "High",
        ),
        row(
            "JOB-NLP-002",
            "NLP Research Engineer",
            "Natural Language Processing",
            "Senior",
            7,
            "PhD",
            340000,
            320000,
            365000,
            "Boston",
            "United States",
            "Remote",
            "Medium",
            "Technology",
            "natural language processing; semantic search; LLM fine-tuning",
            20.0,
            90,
            14.0,
            8.8,
            2025,
            11,
            1,
            1,
            1,
            "High",
        ),
        row(
            "JOB-UK-AI-001",
            "AI Engineer",
            "Machine Learning",
            "Mid",
            5,
            "MS",
            95000,
            88000,
            102000,
            "London",
            "United Kingdom",
            "Hybrid",
            "Medium",
            "Finance",
            "TensorFlow; production models; UK payroll",
            10.0,
            82,
            7.0,
            7.0,
            2025,
            5,
            0,
            0,
            0,
            "Mid",
        ),
        row(
            "JOB-UK-DS-001",
            "Data Scientist",
            "Data Science",
            "Mid",
            4,
            "MS",
            82000,
            76000,
            88000,
            "Manchester",
            "United Kingdom",
            "Hybrid",
            "Medium",
            "Retail",
            "statistics; experimentation; forecasting; UK based",
            8.0,
            78,
            6.0,
            6.8,
            2025,
            5,
            0,
            0,
            0,
            "Mid",
        ),
    ]
    return seeds


def _filler_rows(start: int, count: int) -> list[dict]:
    titles = [
        ("Computer Vision Engineer", "Computer Vision", "Mid", 95000, "Amsterdam", "Netherlands"),
        ("MLOps Engineer", "MLOps", "Senior", 165000, "Dublin", "Ireland"),
        ("Data Engineer", "Data Engineering", "Mid", 125000, "Paris", "France"),
        ("AI Product Manager", "Product", "Senior", 185000, "Chicago", "United States"),
        ("Robotics ML Specialist", "Robotics", "Senior", 198000, "Tokyo", "Japan"),
        ("BI Analyst", "Analytics", "Entry", 58000, "Madrid", "Spain"),
        ("Deep Learning Engineer", "Machine Learning", "Senior", 220000, "Zurich", "Switzerland"),
        ("Prompt Engineer", "LLM Applications", "Mid", 145000, "Remote", "United States"),
    ]
    out: list[dict] = []
    for i in range(count):
        t, cat, exp, sal, city, country = titles[i % len(titles)]
        jid = f"JOB-FILL-{start + i:04d}"
        remote = "Remote" if city == "Remote" else "Hybrid"
        out.append(
            row(
                jid,
                t,
                cat,
                exp,
                3 + (i % 8),
                "BS",
                float(sal),
                int(sal * 0.92),
                int(sal * 1.08),
                city,
                country,
                remote,
                "Medium",
                "Technology",
                "Python; SQL; cloud",
                10.0 + (i % 5),
                70 + (i % 20),
                5.0 + (i % 3),
                7.0,
                2025,
                1 + (i % 12),
                1 if exp == "Senior" else 0,
                1 if remote == "Remote" else 0,
                1 if "LLM" in cat or "Prompt" in t else 0,
                "Mid",
            )
        )
    return out


def main() -> None:
    if DEFAULT_RAW.is_file() and is_kaggle_dataset(DEFAULT_RAW):
        n = row_count(DEFAULT_RAW)
        print(f"Kaggle CSV already at {DEFAULT_RAW} ({n} rows); not overwriting.")
        return
    if DOWNLOADS_CSV.is_file() and is_kaggle_dataset(DOWNLOADS_CSV):
        print(f"Real dataset found at {DOWNLOADS_CSV}")
        print(f"Run: ./scripts/import_kaggle_csv.sh {DOWNLOADS_CSV}")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rows = _seed_rows() + _filler_rows(start=100, count=70)
    with OUT.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {len(rows)} rows to {OUT}")


if __name__ == "__main__":
    main()
